version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.11.0
    steps:
      - checkout
      - run: npm i
      - run: npm run build
      - run: npm run lint
      - run: npm t

  beta-release:
    docker:
      - image: circleci/node:12.11.0
    steps:
      - checkout
      - run: npm i
      - run: npm run build
      - run: npm run lint
      - run: npm t
      - run: sh .circleci/git-login.sh
      - run: sh .circleci/npm-login.sh
      - run: sh .circleci/release.beta.sh

workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
                - beta

      - beta-release:
          filters:
            branches:
              only: beta